[package]
name = "comn"
version = "0.1.0"
authors = ["赵宇龙 <zhaoyulong@qianxin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pmacros = { path = "./src/proc_macro" }
